{% set name = "nerval" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f296ed52e7b9d501a00f92cfb5daecfcf67d493d190f04d54b3d72cfccf23b69

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pandas
    - numpy
    - matplotlib-base
    - scikit-learn
    - python >=3.6

test:
  imports:
    - nerval

about:
  home: https://github.com/mdadda/nerval
  license: MIT
  license_family: MIT
  license_file: LICENCE.txt
  summary: Entity-level confusion matrix and classification report to evaluate Named Entity Recognition (NER) models.
  doc_url:
  dev_url: https://github.com/mdadda/nerval

extra:
  recipe-maintainers:
    - mdadda
